### ISSUE TITLE
Compilation failed: unused parameter 'player'

### ISSUE THREAD

**Issue by Squizzy911** [azerothcore/mod-solo-lfg#1]
Hey,

the module doesnt compile on standard installation. the "docker fix" worked for me.

```
/home/azerothcore/azerothcore-wotlk/modules/mod-solo-lfg/src/Lfg_Solo.cpp:40:25: fatal error: unused parameter 'player' [-Wunused-parameter]

   void OnLogin(Player* player)
```

**Comment by EmilianoRojas** [comment]
it doesnt compile for me either

**Comment by BarbzYHOOL** [comment]
remove the unused parameter

**Comment by pangolp** [comment]
Hello, the date of the issue is 3 years ago, so I will conclude that it was fixed some time ago. In fact, the module was recently updated and passed all the tests, so this bug should no longer occur. If the problem persists, please feel free to create a new issue, providing the necessary information so that we can update or correct the problem. Thank you.
