### ISSUE TITLE
replace patch implementing some hooks on AC

### ISSUE THREAD

**Issue by Helias** [azerothcore/mod-solo-lfg#15]

**Comment by locus313** [comment]
opened a feature request in the main repo https://github.com/azerothcore/azerothcore-wotlk/issues/5657

**Comment by pangolp** [comment]
Hello, what is the current status of this issue, are those hooks still missing, and can you tell exactly which hooks are still missing? If possible, if you could close the issue and create a new one, providing the necessary data, it would be great. I would like the issues that are currently open to be related to current topics. Because I saw that there were many old or discontinued issues. So I await your comments, to know what to do with this issue.

**Comment by Helias** [comment]
I see only one patch in the repository [docker.patch](https://github.com/azerothcore/mod-solo-lfg/blob/master/docker.patch), that probably can be implemented easily in the project

```C++
// replacing this
void OnLogin(Player* player)

// with this
void OnLogin(Player* /*player*/)
```

this could replace the docker patch
