### ISSUE TITLE
On death you cannot return to the instance to get your body

### ISSUE THREAD

**Issue by headdinner** [azerothcore/mod-solo-lfg#16]
When you die or teleport out of the dungeon you are removed from queue, if you are dead and enter the instance you are still dead and cannot retrieve your body.

**Comment by Valoriaz** [comment]
can confirm it

**Comment by markvetx** [comment]
+1

**Comment by pagimu** [comment]
+1

**Comment by corsairs** [comment]
I confirm this god does not give the opportunity to play the game even after leaving the game

**Comment by ajgration** [comment]
Is this able to get fixed? Obviously it still works if you don't die, but sometimes things happen and it's frustrating to lose your whole dungeon progress.

I remember running a repack a while ago called "BrooksTech AzerothCore Solo Repack", that used this module and found a workaround to fix the issue. I believe the fix was it put you in to a party solo, as I remember getting need/greed rolls. Just a shame it was never posted here.

**Comment by dunjeon** [comment]
> Is this able to get fixed? Obviously it still works if you don't die, but sometimes things happen and it's frustrating to lose your whole dungeon progress.
> 
> I remember running a repack a while ago called "BrooksTech AzerothCore Solo Repack", that used this module and found a workaround to fix the issue. I believe the fix was it put you in to a party solo, as I remember getting need/greed rolls. Just a shame it was never posted here.

It wasn't posted here because the module I sued for the repack was written from scratch and predates this one. My work around wasn't elegant. In the repack, I had another module that did a few things to help the solo experience. If the player died, I would check to see if they were solo and, in a dungeon / raid, and if those conditions were true, I would auto res the player (keeping them in the dungeon) and slap a divine intervention on them.

**Comment by pangolp** [comment]
Is this problem still ongoing? I am asking, to know if the issue should be closed or not. As far as I can see, it is almost 1 year old, and my intention is to try to leave the recent issues. Not to mention, the module has been updated a few times, but I don't know if it includes this functionality or not. In any case, we could close this issue, create a new one and provide as much information as possible, so that some developer can see the problem and try to solve it.

**Comment by headdinner** [comment]
Just checked it out and it has been resolved.
