### ISSUE TITLE
Money not being looted.

### ISSUE THREAD

**Issue by Juggalo187** [azerothcore/mod-solo-lfg#34]
Money isn't being looted. I can't find any reports of this issue, so I have no idea what's going on.

**Comment by pangolp** [comment]
> Money isn't being looted. I can't find any reports of this issue, so I have no idea what's going on.

With this information, it will be difficult for a person to reproduce the problem and for us to determine the problem that exists. Or perhaps, due to the time that has passed, this problem no longer exists and the module is currently working fine. If the problem persists, please re-create an issue by filling in all the data in the form, so that we can have a little more information and be able to solve the problem. Thank you.
